export const citiesByState = {
    "Delhi": [
      "New Delhi",
      "Delhi",
      "Noida",
      "Gurgaon",
      "Faridabad",
      "Ghaziabad",
      "Greater Noida",
      "Loni",
      "Dwarka",
      "Kalkaji",
      "Mayur Vihar",
      "Pitampura",
      "Vasant Kunj",
      "Vasant Vihar",
      "Connaught Place",
      "Saket",
      "Chanakyapuri",
      "Karol Bagh",
      "Rohini",
      "Lajpat Nagar",
      "Nehru Place",
      "Okhla",
      "Hauz Khas",
      "South Delhi",
      "East Delhi",
      "North Delhi",
      "West Delhi",
      "Central Delhi",
      "Shahdara",
      "Patparganj",
      "Model Town",
      "Dilshad Garden",
      "Rajouri Garden",
      "Paharganj",
      "Jangpura",
      "Sarita Vihar",
      "Mukherjee Nagar",
      "Preet Vihar",
      "Daryaganj",
      "Vikas Puri",
      "Munirka",
      "Kirti Nagar",
      "Civil Lines",
      "Khan Market",
      "Laxmi Nagar",
      "Kamla Nagar",
      "Ashok Vihar",
      "Defence Colony",
      "Geeta Colony",
      "Malviya Nagar",
      "Safdarjung",
      "Kailash Colony",
      "Green Park",
      "Shalimar Bagh",
      "Chandni Chowk",
      "Najafgarh",
      "Punjabi Bagh",
      "Hauz Qazi",
      "Sadar Bazaar",
      "Vivek Vihar"
   
    
  ],
    "Haryana":
    [
      "Ambala",
      "Ambala Cantt",
      "Asankhurd",
      "Babain",
      "Bahadurgarh",
      "Barara",
      "Barwala",
      "Bawal",
      "Bhiwani",
      "Charkhi Dadri",
      "Cheeka",
      "Dharuhera",
      "Ellenabad",
      "Faridabad",
      "Fatehabad",
      "Ganaur",
      "Gharaunda",
      "Gohana",
      "Gorakhpur",
      "Gurgaon",
      "Hansi",
      "Hasangarh",
      "Hisar",
      "Hodal",
      "Indri",
      "Jagadhri",
      "Jakhal",
      "Jhajjar",
      "Jind",
      "Julana",
      "Kaithal",
      "Kalanaur",
      "Kalka",
      "Karnal",
      "Kharkhauda",
      "Kosli",
      "Kurukshetra",
      "Ladwa",
      "Mahendragarh",
      "Mandi Dabwali",
      "Naraingarh",
      "Narwana",
      "Narnaund",
      "Narnaul",
      "Narwana",
      "Nilokheri",
      "Nuh",
      "Palwal",
      "Panchkula",
      "Panipat",
      "Pehowa",
      "Pinjore",
      "Pundri",
      "Rania",
      "Ratia",
      "Rewari",
      "Rohtak",
      "Safidon",
      "Samalkha",
      "Shahabad",
      "Sirsa",
      "Siwani",
      "Sohna",
      "Sonipat",
      "Thanesar",
      "Tohana",
      "Tosham",
      "Uchana",
      "Yamuna Nagar"
    ],
   
    "Uttarakhand": ["Dehradun","Haridwar"]
    // Add more states and their cities as needed
  };