export const citiesByState = {
    "Delhi": [
      "New Delhi",
      "Delhi",
      "Noida",
      "Gurgaon",
      "Faridabad",
      "Ghaziabad",
      "Greater Noida",
      "Loni",
      "Dwarka",
      "Kalkaji",
      "Mayur Vihar",
      "Pitampura",
      "Vasant Kunj",
      "Vasant Vihar",
      "Connaught Place",
      "Saket",
      "Chanakyapuri",
      "Karol Bagh",
      "Rohini",
      "Lajpat Nagar",
      "Nehru Place",
      "Okhla",
      "Hauz Khas",
      "South Delhi",
      "East Delhi",
      "North Delhi",
      "West Delhi",
      "Central Delhi",
      "Shahdara",
      "Patparganj",
      "Model Town",
      "Dilshad Garden",
      "Rajouri Garden",
      "Paharganj",
      "Jangpura",
      "Sarita Vihar",
      "Mukherjee Nagar",
      "Preet Vihar",
      "Daryaganj",
      "Vikas Puri",
      "Munirka",
      "Kirti Nagar",
      "Civil Lines",
      "Khan Market",
      "Laxmi Nagar",
      "Kamla Nagar",
      "Ashok Vihar",
      "Defence Colony",
      "Geeta Colony",
      "Malviya Nagar",
      "Safdarjung",
      "Kailash Colony",
      "Green Park",
      "Shalimar Bagh",
      "Chandni Chowk",
      "Najafgarh",
      "Punjabi Bagh",
      "Hauz Qazi",
      "Sadar Bazaar",
      "Vivek Vihar"
    
  ],
    "Haryana":
    [
      "Ambala",
      "Ambala Cantt",
      "Asankhurd",
      "Babain",
      "Bahadurgarh",
      "Barara",
      "Barwala",
      "Bawal",
      "Bhiwani",
      "Charkhi Dadri",
      "Cheeka",
      "Dharuhera",
      "Ellenabad",
      "Faridabad",
      "Fatehabad",
      "Ganaur",
      "Gharaunda",
      "Gohana",
      "Gorakhpur",
      "Gurgaon",
      "Hansi",
      "Hasangarh",
      "Hisar",
      "Hodal",
      "Indri",
      "Jagadhri",
      "Jakhal",
      "Jhajjar",
      "Jind",
      "Julana",
      "Kaithal",
      "Kalanaur",
      "Kalka",
      "Karnal",
      "Kharkhauda",
      "Kosli",
      "Kurukshetra",
      "Ladwa",
      "Mahendragarh",
      "Mandi Dabwali",
      "Naraingarh",
      "Narwana",
      "Narnaund",
      "Narnaul",
      "Narwana",
      "Nilokheri",
      "Nuh",
      "Palwal",
      "Panchkula",
      "Panipat",
      "Pehowa",
      "Pinjore",
      "Pundri",
      "Rania",
      "Ratia",
      "Rewari",
      "Rohtak",
      "Safidon",
      "Samalkha",
      "Shahabad",
      "Sirsa",
      "Siwani",
      "Sohna",
      "Sonipat",
      "Thanesar",
      "Tohana",
      "Tosham",
      "Uchana",
      "Yamuna Nagar"
    ],

      "Punjab": [
        "Abohar",
        "Ahmedgarh",
        "Amritsar",
        "Barnala",
        "Batala",
        "Bathinda",
        "Begowal",
        "Bhadaur",
        "Bhikhiwind",
        "Budhlada",
        "Chandigarh",
        "Dakha",
        "Dera Baba Nanak",
        "Dera Bassi",
        "Dharamkot",
        "Dhuri",
        "Dinanagar",
        "Ellenabad",
        "Fatehgarh Churian",
        "Fatehgarh Sahib",
        "Faridkot",
        "Fazilka",
        "Firozpur",
        "Ghanaur",
        "Gidderbaha",
        "Gobindgarh",
        "Gurdaspur",
        "Hoshiarpur",
        "Jagraon",
        "Jaitu",
        "Jalalabad",
        "Jalalabad West",
        "Jalandhar",
        "Jandiala",
        "Jhunir",
        "Joga",
        "Kahnuwan",
        "Kailash Colony",
        "Kapurthala",
        "Karol Bagh",
        "Kharar",
        "Khem Karan",
        "Kirti Nagar",
        "Kosli",
        "Kot Fatta",
        "Kotkapura",
        "Kurali",
        "Lajpat Nagar",
        "Laxmi Nagar",
        "Lehra Gaga",
        "Loni",
        "Ludhiana",
        "Majitha",
        "Malviya Nagar",
        "Malerkotla",
        "Mandi Dabwali",
        "Mandi Gobindgarh",
        "Mansa",
        "Maur",
        "Moga",
        "Mohali",
        "Morinda",
        "Mukherjee Nagar",
        "Muktsar",
        "Mullanpur",
        "Nabha",
        "Nakodar",
        "Nangal",
        "Nawa Shahar",
        "Nawanshahr",
        "Nehru Place",
        "Nurmahal",
        "Paharganj",
        "Pakhowal",
        "Patiala",
        "Patti",
        "Payal",
        "Pehowa",
        "Phagwara",
        "Pitampura",
        "Pundri",
        "Punjabi Bagh",
        "Qadian",
        "Rajpura",
        "Ramdass",
        "Rampura",
        "Rampura Phul",
        "Rampuraphul",
        "Rania",
        "Ratia",
        "Raikot",
        "Rampuraphul",
        "Ropar",
        "Rustam",
        "Rurka Kalan",
        "Safdarjung",
        "Sahnewal",
        "Saket",
        "Sanaur",
        "Sangat",
        "Sangrur",
        "Sardulgarh",
        "Sarhind",
        "Sarita Vihar",
        "Sawai Madhopur",
        "Sekhewal",
        "Sekhon Nagar",
        "Sekhwan",
        "Shahabad",
        "Shahdara",
        "Shahkot",
        "Shalimar Bagh",
        "Shekhpura",
        "Sirkap",
        "Sohna",
        "Sultanpur Lodhi",
        "Sunam",
        "Surti",
        "Talwandi Bhai",
        "Talwandi Sabo",
        "Talwara",
        "Tappa",
        "Tappa Mandi",
        "Tarn Taran",
        "Tarn Taran Sahib",
        "Thanesar",
        "Tosham",
        "Uchana",
        "Uklanamandi",
        "Vasant Kunj",
        "Vasant Vihar",
        "Vikas Puri",
        "Vivek Vihar",
        "Zira",
        "Zirakpur"
        // Add more cities and towns in Punjab as needed
      ],
    
   
    "Uttarakhand": ["Dehradun","Haridwar","Roorkee","Nanital"]
    // Add more states and their cities as needed
  };