export const indianStates = {
    AndhraPradesh: "Andhra Pradesh",
    ArunachalPradesh: "Arunachal Pradesh",
    Assam: "Assam",
    Bihar: "Bihar",
    Delhi: "Delhi",
    Chandigarh: "Chandigarh",
    Chhattisgarh: "Chhattisgarh",
    Goa: "Goa",
    Gujarat: "Gujarat",
    Haryana: "Haryana",
    HimachalPradesh: "Himachal Pradesh",
    Jharkhand: "Jharkhand",
    Karnataka: "Karnataka",
    Kerala: "Kerala",
    Lakshadweep: "Lakshadweep",
    MadhyaPradesh: "Madhya Pradesh",
    Maharashtra: "Maharashtra",
    Manipur: "Manipur",
    Meghalaya: "Meghalaya",
    Mizoram: "Mizoram",
    Nagaland: "Nagaland",
    Odisha: "Odisha",
    Puducherry: "Puducherry",
    Punjab: "Punjab",
    Rajasthan: "Rajasthan",
    Sikkim: "Sikkim",
    TamilNadu: "Tamil Nadu",
    Telangana: "Telangana",
    Tripura: "Tripura",
    UttarPradesh: "Uttar Pradesh",
    Uttarakhand: "Uttarakhand",
    WestBengal: "West Bengal",
    // AndamanAndNicobarIslands: "Andaman and Nicobar Islands",
    
    // DadraAndNagarHaveliAndDamanAndDiu: "Dadra and Nagar Haveli and Daman and Diu",
    
  };
  
  // console.log(indianStates);
  